# Generated by Django 6.0.3 on 2026-04-07 03:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='URLScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=2048, verbose_name='Scanned URL')),
                ('result', models.CharField(choices=[('phishing', 'Phishing'), ('legitimate', 'Legitimate')], max_length=20)),
                ('confidence', models.FloatField(help_text='Confidence score (0–100)')),
                ('scanned_at', models.DateTimeField(auto_now_add=True)),
                ('features_json', models.JSONField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'URL Scan',
                'verbose_name_plural': 'URL Scans',
                'ordering': ['-scanned_at'],
            },
        ),
    ]
